site_name: LoopDocs

theme:
    name: material
    language: en
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
        - content.tooltips
    logo: loop-logo.png
    favicon: loop-logo.png
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default 
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to system preference

# repo_url: https://github.com/LoopKit/Loop

extra_css:
    - stylesheets/extra.css
    - stylesheets/primary-color.css


markdown_extensions:
    - meta
    - abbr
    - admonition
    - attr_list
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets:
        auto_append:
            - includes/tooltip-list.txt
    - toc:
        permalink: true
        permalink_title: Anchor link to this Header on this Page
        toc_depth: 3
        title: Headers on this Page
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search

nav:
- Home: 'index.md'
- Intro:
    - 'LoopDocs Overview': 'intro/overview-intro.md'
    - 'LoopDocs How-to': 'intro/loopdocs-how-to.md'
- Build:
    - 'Build Overview': 'build/overview.md'
    - 'Compatible Computer': 'build/step1.md'
    - 'Compatible iPhone/iPod': 'build/step2.md'
    - 'Compatible Pump': 'build/step3.md'
    - 'Compatible CGM': 'build/step4.md'
    - 'Order a RileyLink': 'build/step5.md'
    - 'Apple Developer Program': 'build/step6.md'
    - 'Download Xcode': 'build/step8.md'
    - 'Xcode Preferences': 'build/step9.md'
    - 'Test Settings': 'build/step10.md'
    - 'Loop Data': 'build/step11.md'
    - 'Meet the Community': 'build/step12.md'
    - 'Build Loop App': 'build/step14.md'
    - 'Oh dear! Build errors?': 'build/build_errors.md'
    - 'Updating/Rebuilding': 'build/updating.md'
    - 'Loop-dev': 'build/step13.md'
- Set Up:
    - 'Set Up Overview': 'operation/overview.md'
    - 'Step 1: Health Permissions': 'build/health.md'
    - 'Step 2: Add Pump':
        - 'Add Medtronic': 'operation/loop-settings/mdt-pump.md'
        - 'Add Omnipod': 'operation/loop-settings/omnipod-pump.md'
    - 'Step 3: Add CGM': 'operation/loop-settings/cgm.md'
    - 'Step 4: Configurations': 'operation/loop-settings/configurations.md'
    - 'Step 5: Loop Services': 'operation/loop-settings/services.md'
    - 'Loop Displays': 'operation/loop-settings/displays.md'
    - 'RileyLink Display': 'operation/loop-settings/rileylink.md'
    - 'Pump Settings': 'operation/loop-settings/pump-commands.md'
- Operate:
    - 'Open Loop': 'operation/loop/open-loop.md'
    - 'Closed Loop': 'operation/loop/close-loop.md'
    - 'Meal Entries': 'operation/features/carbs.md'
    - 'Bolus': 'operation/features/bolus.md'
    - 'Overrides': 'operation/features/workout.md'
    - 'Loop Notifications': 'operation/features/notifications.md'
    - 'Pre-meal target': 'operation/features/premeal.md'
    - 'Using ICE info': 'operation/features/ice.md'
    - 'Apple Watch': 'operation/features/watch.md'
    - 'iPhone widget': 'operation/features/widget.md'
    - Loop Tips: 'operation/loop/looptips.md'
    - Algorithm:
        - 'Algorithm Overview': 'operation/algorithm/overview.md'
        - 'Bolus Recommendations': 'operation/algorithm/bolus.md'
        - 'Glucose Prediction': 'operation/algorithm/prediction.md'
        - 'Temp Basal Adjustments': 'operation/algorithm/temp-basal.md'
- Troubleshoot:
    - 'Troubleshooting Overview': 'troubleshooting/overview.md'
    - 'Loop App crashes': 'troubleshooting/loop-crashing.md'
    - 'Red Loop': 'troubleshooting/yellow-red-loop.md'
    - 'Pod Pairing Failures': 'troubleshooting/pod-pairing.md'
    - 'Omnipod Faults': 'troubleshooting/omnipod-faults.md'
    - 'MDT Pump Errors': 'troubleshooting/pump-errors.md'
    - 'MDT Pump Battery': 'operation/features/battery.md'
- Loop 3:
    - 'Loop 3 Overview': 'loop-3/loop-3-overview.md'
    - 'Loop 3 Onboarding': 'loop-3/onboarding.md'
    - 'Loop 3 Add CGM': 'loop-3/add-cgm.md'
    - 'Loop 3 Add Pump': 'loop-3/add-pump.md'
    - 'Loop 3 Displays': 'loop-3/displays_v3.md'
    - 'Loop 3 Alerts & Notifications': 'loop-3/alert-notify.md'
    - 'Loop 3 Settings': loop-3/settings.md
    - 'Loop 3 Therapy Settings': 'loop-3/therapy-settings.md'
    - 'Loop 3 Omnipod': loop-3/omnipod.md
    - 'Loop 3 Medtronic': loop-3/medtronic.md
    - 'Loop 3 Features': loop-3/features.md
- 'Version':
    - 'Version Overview': 'version/overview-version.md'
    - 'Loop Releases': 'faqs/release-faqs.md'
    - 'Customize your Loop': 'build/code_customization.md'
    - 'Simulator Build': 'version/simulator.md'
    - 'Loop Development': 'faqs/branch-faqs.md'
    - 'Building Dev': 'build/build-select-dev.md'
    - 'LoopWorkspace': 'build/loopworkspace.md'
- Nightscout:
    - 'Nightscout Overview': 'nightscout/overview.md'
    - 'Brand New NS': 'nightscout/new_user.md'
    - 'Retrofit Existing NS': 'nightscout/update_user.md'
    - 'Setup Troubleshooting': 'nightscout/troublehoot.md'
    - 'Remote Overrides': 'nightscout/remote-overrides.md'
    - 'Nightscout Cross Ref': 'nightscout/ns_crossref.md'
- FAQs:
    - 'FAQs Overview': 'faqs/overview-faqs.md'
    - 'Safety Tips': 'faqs/safety-faqs.md'
    - 'Loop FAQs': 'faqs/FAQs.md'
    - 'Time Change FAQs': 'troubleshooting/time-change.md'
    - 'Omnipod FAQs': 'faqs/omnipod-faqs.md'
    - 'CGM FAQs': 'faqs/cgm-faqs.md'
    - 'Update/Rebuild Loop FAQs': 'faqs/update-faqs.md'
    - 'RileyLink FAQs': 'faqs/rileylink-faqs.md'
    - 'Algorithm FAQs': 'faqs/algorithm-faqs.md'
    - 'Apple Health FAQs': 'faqs/apple-health-faqs.md'
    - 'Glossary': 'faqs/glossary.md'
